/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.synapse.ui.views.login;

import com.formdev.flatlaf.FlatClientProperties;
import com.synapse.Application;
import com.synapse.core.models.Usuario;
import com.synapse.data.dao.UsuarioDAO;
import com.synapse.ui.views.shared.MainForm;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import raven.toast.Notifications;

/**
 *
 * @author FERNANDO
 */
public class FormLogin extends javax.swing.JPanel {
    private final MainForm mainform;

    /**
     * Creates new form FormLogin
     */
    public FormLogin(MainForm mainform) {
        this.mainform = mainform;
        initComponents();
        panelLogin.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:25");
        bntInicioSesion.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    validarUsuario();
                }
            }
        });
    }

    private void validarUsuario() {
        String password = String.valueOf(txtcontraseña.getPassword());
        String email = txtUsuario.getText();

        System.out.println("=== DEBUG LOGIN ===");
        System.out.println("Email ingresado: " + email);
        System.out.println("Password ingresado: " + password);
        System.out.println("Password vacío: " + password.isEmpty());
        System.out.println("Email vacío: " + email.isEmpty());

        if (password.isEmpty() || email.isEmpty()) {
            System.out.println("❌ Campos vacíos detectados");
            camposVacios();
            return;
        }

        System.out.println("✅ Campos llenos, intentando login...");
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        System.out.println("UsuarioDAO creado");

        Usuario usuario = usuarioDAO.login(email, password);
        System.out.println("Resultado login: " + (usuario != null ? "SUCCESS" : "FAIL"));

        if (usuario != null) {
            System.out.println("✅ Login exitoso para: " + usuario.getNombre());
            mensajeVerificado();
            Application.iniciarSesionUsuario(usuario);
        } else {
            System.out.println("❌ Login fallido - credenciales incorrectas");
            rellenoDatosError();
        }
        System.out.println("===================");
    }

    private void camposVacios() {
        Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                "Credenciales en blanco");
    }

    private void rellenoDatosError() {
        Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER,
                "Credenciales no validas intentelo nuevamente");

    }

    private void mensajeVerificado() {
        Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_RIGHT,
                "Bienvenido\nInico de sesion exitoso");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new com.synapse.ui.views.login.Background();
        panelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcontraseña = new com.synapse.ui.lib.swing.PasswordField();
        txtUsuario = new com.synapse.ui.lib.swing.TextField();
        jLabel3 = new javax.swing.JLabel();
        bntInicioSesion = new com.synapse.ui.components.ButtonAction();

        setBackground(new java.awt.Color(245, 245, 245));

        panelLogin.setBackground(new java.awt.Color(19, 19, 19));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Email :");
        panelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña :");
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtcontraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcontraseña.setHint("Ingrese su contraseña");
        panelLogin.add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 380, 35));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.setHint("Ingrese su correo");
        panelLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 380, 35));

        jLabel3.setFont(new java.awt.Font("FiraCode Nerd Font", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese sus credenciales para acceder");
        panelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 350, 34));

        bntInicioSesion.setBackground(new java.awt.Color(255, 255, 255));
        bntInicioSesion.setForeground(new java.awt.Color(0, 0, 0));
        bntInicioSesion.setText("Iniciar Sesion");
        bntInicioSesion.setFont(new java.awt.Font("FiraCode Nerd Font", 1, 14)); // NOI18N
        bntInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInicioSesionActionPerformed(evt);
            }
        });
        bntInicioSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bntInicioSesionKeyPressed(evt);
            }
        });
        panelLogin.add(bntInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 280, 39));

        background1.add(panelLogin);
        panelLogin.setBounds(90, 190, 460, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 1286, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void bntInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bntInicioSesionActionPerformed
        // TODO add your handling code here:
        validarUsuario();
    }// GEN-LAST:event_bntInicioSesionActionPerformed

    private void bntInicioSesionKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_bntInicioSesionKeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_bntInicioSesionKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.synapse.ui.views.login.Background background1;
    private com.synapse.ui.components.ButtonAction bntInicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelLogin;
    private com.synapse.ui.lib.swing.TextField txtUsuario;
    private com.synapse.ui.lib.swing.PasswordField txtcontraseña;
    // End of variables declaration//GEN-END:variables
}
