package com.synapse.ui.views.admin;

import com.synapse.core.models.Usuario;
import com.synapse.data.dao.UsuarioDAO;
import raven.toast.Notifications;

/**
 * Dialog para editar usuarios
 * 
 * @author FERNANDO
 */
public class EditarUsuario extends javax.swing.JDialog {

    private final Usuario usuario;
    private final UsuarioDAO usuarioDAO;
    private boolean guardado = false;

    /**
     * Creates new form EditarUsuario
     */
    public EditarUsuario(java.awt.Frame parent, Usuario usuario) {
        super(parent, true);
        this.usuario = usuario;
        this.usuarioDAO = new UsuarioDAO();
        initComponents();
        configurarComboRol();
        cargarDatos();
        configurarBoton();
        setLocationRelativeTo(parent);
    }

    private void configurarComboRol() {
        comboRol.removeAllItems();
        comboRol.addItem("empleado");
        comboRol.addItem("gerente");
        comboRol.addItem("administrador");
    }

    private void cargarDatos() {
        jTextField1.setText(usuario.getNombre());
        txtEmail.setText(usuario.getEmail());

        // Seleccionar rol actual
        String rolActual = usuario.getRol();
        if (rolActual != null) {
            for (int i = 0; i < comboRol.getItemCount(); i++) {
                if (comboRol.getItemAt(i).equalsIgnoreCase(rolActual)) {
                    comboRol.setSelectedIndex(i);
                    break;
                }
            }
        }
    }

    private void configurarBoton() {
        buttonAction1.addActionListener(e -> guardarCambios());
    }

    private void guardarCambios() {
        String nombre = jTextField1.getText().trim();
        String email = txtEmail.getText().trim();
        String rol = (String) comboRol.getSelectedItem();

        // Validaciones
        if (nombre.isEmpty()) {
            Notifications.getInstance().show(
                    Notifications.Type.WARNING,
                    Notifications.Location.TOP_CENTER,
                    "⚠️ El nombre es obligatorio");
            return;
        }

        if (email.isEmpty() || !email.contains("@")) {
            Notifications.getInstance().show(
                    Notifications.Type.WARNING,
                    Notifications.Location.TOP_CENTER,
                    "⚠️ Ingrese un email válido");
            return;
        }

        // Actualizar usuario
        usuario.setNombre(nombre);
        usuario.setEmail(email);
        usuario.setRol(rol);

        boolean exito = usuarioDAO.actualizarUsuarioAdmin(usuario);

        if (exito) {
            guardado = true;
            Notifications.getInstance().show(
                    Notifications.Type.SUCCESS,
                    Notifications.Location.TOP_CENTER,
                    "✅ Usuario actualizado correctamente");
            dispose();
        } else {
            Notifications.getInstance().show(
                    Notifications.Type.ERROR,
                    Notifications.Location.TOP_CENTER,
                    "❌ Error al actualizar usuario");
        }
    }

    public boolean isGuardado() {
        return guardado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboRol = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        buttonAction1 = new com.synapse.ui.components.ButtonAction();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre Completo *");

        jLabel2.setText("Correo Electronico *");

        jLabel3.setText("Rol *");

        // Combo configurado en código

        buttonAction1.setText("Editar Usuario");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Editar Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(buttonAction1, javax.swing.GroupLayout.DEFAULT_SIZE, 362,
                                                        Short.MAX_VALUE)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel3)
                                                .addComponent(jTextField1)
                                                .addComponent(txtEmail)
                                                .addComponent(comboRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)))
                                .addContainerGap(46, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboRol, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(buttonAction1, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.synapse.ui.components.ButtonAction buttonAction1;
    private javax.swing.JComboBox<String> comboRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
