package com.synapse.ui.views.empleado;

import com.formdev.flatlaf.FlatClientProperties;
import com.synapse.core.models.Tarea;
import com.synapse.core.models.Usuario;
import com.synapse.data.dao.TareaDAO;
import com.synapse.ui.components.TaskCardEmpleado; // ¡Usamos la tarjeta nueva!
import java.util.List;
import javax.swing.JPanel;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingWorker;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author FERNANDO
 */
public class formMisTareas extends javax.swing.JPanel {

    private final Usuario usuarioLogueado;
    private final TareaDAO tareaDAO;

    public formMisTareas(Usuario usuario) {
        this.usuarioLogueado = usuario;
        this.tareaDAO = new TareaDAO();

        initComponents();
        configurarPanel();
        cargarTareasConSwingWorker();
    }

    private void configurarPanel() {
        panelMisTareas.setLayout(new MigLayout("wrap, fillx, gapy 10", "[fill]"));
    }

    /**
     * ¡NUEVO! Carga las tareas del empleado en un hilo de fondo.
     */
    private void cargarTareasConSwingWorker() {

        SwingWorker<List<Tarea>, Void> worker = new SwingWorker<List<Tarea>, Void>() {
            @Override
            protected List<Tarea> doInBackground() throws Exception {
                // ESTO SE EJECUTA EN OTRO HILO
                return tareaDAO.getTareasPorUsuario(usuarioLogueado.getIdUsuario());
            }

            @Override
            protected void done() {
                // ESTO SE EJECUTA DE VUELTA EN EL HILO DE UI
                try {
                    List<Tarea> misTareas = get();

                    panelMisTareas.removeAll();
                    if (misTareas.isEmpty()) {
                        // (Mostrar JLabel de "No hay tareas")
                    } else {
                        for (Tarea tarea : misTareas) {
                            TaskCardEmpleado card = new TaskCardEmpleado(tarea, tareaDAO);
                            panelMisTareas.add(card, "growx");
                        }
                    }
                    panelMisTareas.revalidate();
                    panelMisTareas.repaint();

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        worker.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        panelMisTareas = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        panelHeader.setOpaque(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Mis Tareas");
        lblTitulo.setToolTipText("");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblTitulo)
                .addContainerGap(524, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(41, 41, 41))
        );

        add(panelHeader, java.awt.BorderLayout.PAGE_START);

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout panelMisTareasLayout = new javax.swing.GroupLayout(panelMisTareas);
        panelMisTareas.setLayout(panelMisTareasLayout);
        panelMisTareasLayout.setHorizontalGroup(
            panelMisTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        panelMisTareasLayout.setVerticalGroup(
            panelMisTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(panelMisTareas);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMisTareas;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
